backend:
  name: git
  repo: username/repo-name # Ganti dengan nama repository GitHub Anda
  branch: main

media_folder: "static/uploads" # Folder untuk menyimpan file media
public_folder: "/uploads"

# Konfigurasi Hero Section
      ...
collections:
  - name: "hero_section"
    label: "Hero Section"
    file: "index.html" # File tempat hero section berada
    fields:
      - { name: "introduction", label: "Perkenalan", widget: "string" }
      - { name: "title", label: "Judul", widget: "string" }
      - { name: "description", label: "Deskripsi", widget: "markdown" }
      - { name: "button1_text", label: "Teks Tombol 1", widget: "string" }
        name: "button1_link"
        label: "Link Tombol 1"
        widget: "string"
      - { name: "button2_text", label: "Teks Tombol 2", widget: "string" }
        name: "button2_link"
        label: "Link Tombol 2"
        widget: "string"
      - { name: "image", label: "Gambar", widget: "image" }

collections:
  - name: "hero_section"
    label: "Hero Section"
    file: "index.html"
    fields:

# Konfigurasi About Section
      ...
  - name: "about_section"
    label: "About Section"
    file: "index.html"
    fields:
      - { name: "image", label: "Gambar", widget: "image" }
      - { name: "subtitle", label: "Subjudul", widget: "string" }
      - { name: "title", label: "Judul", widget: "string" }
      - { name: "description_1", label: "Deskripsi 1", widget: "text" }
      - { name: "description_2", label: "Deskripsi 2", widget: "text" }
      - name: "features"
        label: "Fitur Utama"
        widget: "list"
        fields:
          - { name: "feature", label: "Fitur", widget: "string" }
      - { name: "button_text", label: "Teks Tombol", widget: "string" }
      - { name: "button_link", label: "Link Tombol", widget: "string" }
      - name: "social_links"
        label: "Media Sosial"
        widget: "list"
        fields:
          - { name: "platform", label: "Platform", widget: "string" }
          - { name: "link", label: "Link", widget: "string" }

# Konfigurasi Service Section
      ...
collections:
  - name: "service_section"
    label: "Service Section"
    file: "index.html"
    fields:
      - { name: "subtitle", label: "Subjudul", widget: "string" }
      - { name: "title", label: "Judul", widget: "string" }
      - { name: "description", label: "Deskripsi", widget: "text" }
      - { name: "button_text", label: "Teks Tombol", widget: "string" }
      - { name: "button_link", label: "Link Tombol", widget: "string" }
      - name: "services"
        label: "Layanan"
        widget: "list"
        fields:
          - { name: "icon", label: "Ikon (Font Awesome)", widget: "string" }
          - { name: "title", label: "Judul Layanan", widget: "string" }
          - { name: "description", label: "Deskripsi Layanan", widget: "text" }
          - { name: "link", label: "Tautan", widget: "string" }

# Konfigurasi Feature Section
      ...
collections:
  - name: "feature_section"
    label: "Feature Section"
    file: "index.html"
    fields:
      - { name: "subtitle", label: "Subjudul", widget: "string" }
      - { name: "title", label: "Judul", widget: "string" }
      - { name: "description", label: "Deskripsi", widget: "text" }
      - name: "features"
        label: "Fitur Utama"
        widget: "list"
        fields:
          - { name: "icon", label: "Ikon (Font Awesome)", widget: "string" }
          - { name: "text", label: "Teks Fitur", widget: "string" }
      - name: "counters"
        label: "Data Counter"
        widget: "list"
        fields:
          - { name: "icon", label: "Ikon (Font Awesome)", widget: "string" }
          - { name: "count", label: "Jumlah", widget: "number" }
          - { name: "label", label: "Label", widget: "string" }
      - { name: "image", label: "Gambar", widget: "image" }

# Konfigurasi Projects Section
      ...
collections:
  - name: "projects"
    label: "Projects Section"
    file: "index.html"
    fields:
      - { name: "section_title", label: "Judul Bagian", widget: "string" }
      - { name: "subtitle", label: "Subjudul", widget: "string" }
      - name: "projects"
        label: "Daftar Proyek"
        widget: "list"
        fields:
          - { name: "image", label: "Gambar Proyek", widget: "image" }
          - { name: "title", label: "Nama Proyek", widget: "string" }
          - { name: "rooms", label: "Jumlah Kamar", widget: "number" }
          - { name: "land_area", label: "Luas Tanah (LT)", widget: "string" }
          - { name: "building_area", label: "Luas Bangunan (LB)", widget: "string" }
          - { name: "link", label: "Tautan Detail", widget: "string" }

# Konfigurasi Projects Section
      ...
collections:
  - name: "faqs"
    label: "FAQs"
    folder: "content/faqs"
    create: true
    slug: "{{fields.question | slugify}}"
    fields:
      - { name: "question", label: "Pertanyaan", widget: "string" }
      - { name: "answer", label: "Jawaban", widget: "markdown" }
      - { name: "category", label: "Kategori", widget: "select", options: ["Umum", "Investasi", "Properti"] }
      - { name: "order", label: "Urutan", widget: "number", default: 1 }

# Konfigurasi Teams Section
      ...
collections:
  - name: "team"
    label: "Team"
    folder: "content/team"
    create: true
    slug: "{{fields.name | slugify}}"
    fields:
      - { name: "name", label: "Nama", widget: "string" }
      - { name: "position", label: "Jabatan", widget: "string" }
      - { name: "description", label: "Deskripsi", widget: "markdown" }
      - { name: "image", label: "Foto", widget: "image" }
      - { name: "facebook", label: "Facebook", widget: "string", required: false }
      - { name: "twitter", label: "Twitter", widget: "string", required: false }
      - { name: "instagram", label: "Instagram", widget: "string", required: false }
      - { name: "linkedin", label: "LinkedIn", widget: "string", required: false }
      - { name: "order", label: "Urutan", widget: "number", default: 1 }

# Konfigurasi Teams Section
      ...
collections:
  - name: "testimonial"
    label: "Testimonial"
    folder: "content/testimonials"
    create: true
    slug: "{{fields.client_name | slugify}}"
    fields:
      - { name: "client_name", label: "Nama Klien", widget: "string" }
      - { name: "profession", label: "Profesi", widget: "string" }
      - { name: "feedback", label: "Testimoni", widget: "text" }
      - { name: "image", label: "Foto", widget: "image" }
      - { name: "order", label: "Urutan", widget: "number", default: 1 }
